char *html = 
	"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"  <head>\n"
	"    <meta charset=\"utf-8\">\n"
	"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
	"    <meta name=\"description\" content=\"Varnish status frontend\">\n"
	"    <meta name=\"author\" content=\"Varnish software\">\n"
	"    <link rel=\"icon\" href=\"../../favicon.ico\">\n"
	"    <title>Varnish Status</title>\n"
	"  </head>\n"
	"  <body>\n"
	"    <div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n"
	"      <div class=\"container\">\n"
	"	<div class=\"collapse navbar-collapse\">\n"
	"     	  <ul class=\"nav navbar-nav\">\n"
	"            <li><a class=\"navbar-brand\"href=\"https://github.com/arianna-aondio/libvmod-rtstatus\">GITHUB</a></li>\n"
	"            <li><a class=\"navbar-brand\" href=\"/rtstatus.json\">JSON</a></li>\n"
	"      	  </ul>\n"
	"     	</div>\n"
	"      </div>\n"
	"    </div>\n"
	"</div>\n"
	"<div class=\"jumbotron\">\n"
	"  <div class=\"container\"><h1>VARNISH STATUS</h1></div>\n"
	"</div>\n"
	"<div class=\"container\">\n"
	"  <div class=\"row\">\n"
	"    <div class=\"col-md-4\" id=\"info\"><h2>General infos</h2></div>\n"
	"    <div class=\"col-md-2\"></div>\n"
	"    <div class=\"col-md-3\" id=\"be\">\n"
	"      <h2>Backends overview</h2>\n"
	"    </div>   \n"
	"    <div class=\"col-md-1\" id=\"bevalue\"></div>\n"
	"    <div>\n"
	"      <div class=\"container\">\n"
	"	<table class=\"table table-striped\" id=\"tblbeover\" style=\"white-space: pre;\">\n"
	"	  <thead><tr><th></th><th></th><th></thead>\n"
	"	  <tbody></tbody>\n"
	"	</table>\n"
	"      </div>\n"
	"    </div>\n"
	"  </div>\n"
	"  <h1>Backends:</h1>\n"
	"  <div class=\"backend\">\n"
	"  </div>\n"
	"  <BR>\n"
	"  <a href=\"javascript:openSpoiler('spoilbe')\">\n"
	"    <b>Show details backends</b></a>\n"
	"  <div id=\"spoilbe\" class=\"row\" style=\"display: none;\">\n"
	"    <div class=\"container\">\n"
	"      <table class=\"table table-hover\" id=\"tblbe\" style=\"white-space: pre;width:59%\">\n"
	"	<thead><tr><th></th><th></th><th></thead>\n"
	"	<tbody></tbody>\n"
	"      </table>\n"
	"    </div>\n"
	"  </div>\n"
	"  <br>\n"
	"   <a href=\"javascript:openSpoiler('spoil')\">\n"
	"    <b>Show detailed counters</b></a>\n"
	"  <div id=\"spoil\" class=\"row\" style=\"display: none;\">\n"
	"    <div class=\"container\">\n"
	"      <table class=\"table table-hover\" id=\"tbl\" style=\"white-space: pre;\">\n"
	"	<thead><tr><th>        Description</th><th>Name</th><th>value</th></tr></thead>\n"
	"	<tbody></tbody>\n"
	"      </table>\n"
	"    </div>\n"
	"  </div>\n"
	"  <hr>\n"
	"</div>\n"
	"<div class=\"footer\">\n"
	"  <div class=\"container\">\n"
	"    <p>&copy;Copyright 2014 Varnish Software AS</p>\n"
	"  </div>\n"
	"</div>\n"
	"<script>\n"
	"  function openSpoiler(id){\n"
	" 	 var a = document.getElementById(id).style;\n"
	" 	 a.display = a.display=='block'?'none':'block'}\n"
	"  function openSpoiler(id){\n"
	" 	 var a = document.getElementById(id).style;\n"
	" 	 a.display = a.display=='block'?'none':'block'}\n"
	"  function info(){\n"
	" 	 $.getJSON( \"/rtstatus.json\", function( data ) {\n"
	" 		 var items = [];\n"
	" 		 var index = 0;\n"
	" 		 items.push(\"<p>\"+ \"<b>Varnish version: </b> \" + data.varnish_version + \"</p>\");\n"
	" 		 items.push(\"<p>\"+ \"<b>Server identity: </b> \" + data.server_id + \"</p>\");\n"
	" 		 items.push(\"<p>\"+ \"<b>Varnish uptime: </b> \" + data.uptime + \"</p>\");\n"
	" 		 items.push(\"<p>\"+ \"<b>Hitrate: </b>\"+ \" \" + data.hitrate + \" %\"+ \"</p>\");\n"
	" 		 items.push(\"<p>\"+ \"<b>Load: </b>\"+ \" \" + data.load + \" req/s\"+ \"</p>\");\n"
	" 		 $(\"#info\").html(\"\");\n"
	" 		 $( \"<p/>\", { \"class\": \"my-new-list\", html: items.join( \"\" )}).appendTo( \"#info\" );\n"
	" 		 var items = [];\n"
	" 		 var cont = 0;\n"
	" 		 var i = 1;\n"
	" 		 $.each( data, function( key, val ) {\n"
	"  			if(val.type === \"MAIN\" && key.match(\"backend\")){\n"
	"  				items.push( \"<p>\" + \"<b>\" + val.descr + \"</b>\"  +\" :  \" + \"</p>\" );\n"
	"  		 }});\n"
	"		 $(\"#be\").html(\"\");\n"
	"  		 $( \"<p/>\", {\"class\": \"my-new-list\",html: items.join( \"\" )}).appendTo( \"#be\" );\n"
	"  		 var items = [];\n"
	"  		 var cont = 0;\n"
	"  		 var i = 1;\n"
	"  		 $.each( data, function( key, val ) {\n"
	"  			if(val.type === \"MAIN\" && key.match(\"backend\")){\n"
	"  			items.push( \"<p>\" +  val.value + \"</p>\" );\n"
	"  		 }});\n"
	"  		 $(\"#bevalue\").html(\"\");\n"
	"  		 $( \"<p/>\", {\"class\": \"my-new-list\",html: items.join( \"\" )}).appendTo( \"#bevalue\" );\n"
	"   		 var items = [];\n"
	" 		 var i,j;\n"
	" 		 var cont;\n"
	" 		 $.each( data, function( key, val ) {\n"
	" 			 if(key === \"backend\"){\n"
	" 				 var tmp = data.backend;\n"
	" 			 }\n"
	" 			 if(tmp) {\n"
	" 				 for(i = 0, cont = 0; i < tmp.length;i++){\n"
	" 					 items.push( \"<p>\" + \"<b>Name: </b> \" + tmp[i].name + \" : \" + tmp[i].value + \"</p>\" );\n"
	" 		 }}});\n"
	"		 $(\"div.backend\").html(\"\");\n"
	" 		 $( \"<p/>\", {\"class\": \"my-new-list\", html: items.join( \"\" )}).appendTo( \"div.backend\" );\n"
	" 		 var cont = 0;\n"
	" 		 $('table#tblbe TBODY').html(\"\");\n"
	" 		 $.each(data, function(key, val){\n"
	"  			 if(val.type === \"VBE\"){\n"
	" 				 if(cont % 9 === 0){\n"
	" 					 $('table#tblbe TBODY').append('<tr><td>'+\"\t\"+\"<b>BACKEND : \"+ val.ident+'</td><td>'+\"\t\t\"+\"</b>\" +'</td><td></tr>');\n"
	" 				 }\n"
	" 			 $('table#tblbe TBODY').append('<tr><td>'+\"\t\"+val.descr+'</td><td>'+val.value+'</td><td></tr>');\n"
	" 			 cont++;\n"
	" 		 }});\n"
	" 		 var cont = 0;\n"
	" 		 $('table#tbl TBODY').html(\"\");\n"
	" 		 $.each(data, function(key, val){\n"
	" 		 if(cont > 7){\n"
	" 			 $('table#tbl TBODY').append('<tr><td>'+\"\t\"+key+'</td><td>'+val.descr+'</td><td>'+val.value+'</td><td></tr>');\n"
	" 		 }\n"
	" 		 cont++;\n"
	" 		 });\n"
	" 	 });\n"
	"  };\n"
	"  var myVar = setInterval(function(){info()}, 1000);\n"
	"</script>\n"
	"<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.4.2.min.js\"></script>\n"
	"<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\n"
	"<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css\">\n"
	"<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n"
	"<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n"
	"<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n"
	"</body>\n"
	"</html>\n"
;
