char *html = 	"<!DOCTYPE html>\n"
		"<html lang=\"en\">\n"
		"  <head>\n"
		"    <meta charset=\"utf-8\">\n"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
		"    <meta name=\"description\" content=\"Varnish status frontend\">\n"
		"    <meta name=\"author\" content=\"Varnish software\">\n"
		"    <link rel=\"icon\" href=\"../../favicon.ico\">\n"
		"    <title>Varnish Status</title>\n"
		"  </head>\n"
		"  <body>\n"
		"    <div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n"
		"      <div class=\"container\">\n"
		"        <div class=\"navbar-header\">\n"
		"          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n"
		"            <span class=\"sr-only\">Toggle navigation</span>\n"
		"            <span class=\"icon-bar\"></span>\n"
		"            <span class=\"icon-bar\"></span>\n"
		"            <span class=\"icon-bar\"></span>\n"
		"          </button>\n"
		"          <a class=\"navbar-brand\" href=\"https://github.com/arianna-aondio/libvmod-rtstatus\">Github repository</a>\n"
		"        </div>\n"
		"      </div>\n"
		"    </div>\n"
		"    <div class=\"jumbotron\">\n"
		"      <div class=\"container\">\n"
		"        <h1>VARNISH STATUS</h1>\n"
		"      </div>\n"
		"    </div>\n"
		"    <div class=\"container\">\n"
		"      <div class=\"row\">\n"
		"        <div class=\"col-md-4\" id=\"info\">\n"
		"          <h2>General infos</h2>\n"
		"          <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){info()}, 1000);\n"
		"	    function info(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];	\n"
		"	    var index = 0;\n"
		"	    items.push(\"<p>\"+ \"<b>Varnish version: </b> \" + data.varnish_version + \"</p>\");\n"
		"	    items.push(\"<p>\"+ \"<b>Server identity: </b> \" + data.server_id + \"</p>\");\n"
		"	    items.push(\"<p>\"+ \"<b>Varnish uptime: </b> \" + data.uptime + \"</p>\");\n"
		"	    items.push(\"<p>\"+ \"<b>Hitrate: </b>\"+ \" \" + data.hitrate + \" %\"+ \"</p>\");\n"
		"	    items.push(\"<p>\"+ \"<b>Load: </b>\"+ \" \" + data.load + \" req/s\"+ \"</p>\");\n"
		"	    $(\"#info\").html(\"\");\n"
		"	    $( \"<p/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"#info\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"        </div>\n"
		"	<div class=\"col-md-2\"></div>\n"
		"        <div class=\"col-md-3\" id=\"be\">\n"
		"          <h2>Backends overview</h2>\n"
		"          <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){be()}, 1000);\n"
		"	    function be(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if( val.type === \"MAIN\" && key.match(/backend/)){\n"                                    
		"	    items.push( \"<p>\" + \"<b>\" + val.descr + \"</b>\"  +\" :  \" + \"</p>\" );\n"
		"	    }});\n"
		"	    $(\"#be\").html(\"\");\n"
		"	    $( \"<p/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"#be\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"        </div>\n"
		"	<div class=\"col-md-1\" id=\"bevalue\">\n"
		"	  <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){bevalue()}, 1000);\n"
		"	    function bevalue(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if( val.type === \"MAIN\" && key.match(/backend/)){\n"
		"	    items.push( \"<p>\" +  val.value + \"</p>\" );\n"
		"	    }});\n"
		"	    $(\"#bevalue\").html(\"\");\n"
		"	    $( \"<p/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"#bevalue\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"	</div>\n"
		"      </div>\n"
		"      <hr>\n"
		"      <h1>Backends:</h1>\n"
		"      <div class=\"spoiler\">\n"
		"	<div class=\"backend\">\n"
		"	  <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){backend()}, 1000);\n"
		"	    function backend(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var i,j;\n"
		"	    var cont;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if(key === \"backend\"){\n"
		"	    var tmp = data.backend;\n"
		"	    }\n"
		"	    if(tmp) {\n"
		"	    for(i = 0, cont = 0; i < tmp.length;i++){\n"
		"	    items.push( \"<p>\" + \"<b>Name: </b> \" + tmp[i].name + \" : \" + tmp[i].value + \"</p>\" );\n"
		"	    }}});\n"
		"	    $(\"div.backend\").html(\"\");\n"
		"	    $( \"<p/>\", {\n"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"div.backend\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n       "
		"	</div>\n"
		"      </div>\n"
		"      <script>\n"
		"	function openSpoiler(id){\n"
		"	var a = document.getElementById(id).style;\n"
		"	a.display = a.display==\'block\'?\'none\':\'block\'}\n"
		"      </script>\n"
		"      <BR>\n"
		"      <a href=\"javascript:openSpoiler(\'spoilbe\')\">\n"
		"	<b>Show details backends</b></a>\n"
		"      <div id=\"spoilbe\" class=\"row\" style=\"display: none;\">\n"
		"	<div class=\"col-xs-5\">"
		"	  <h2>Details:</h2>\n"
		"	  <p4>details</p4>\n"
		"	  <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){detail()}, 1000);\n"
		"	    function detail(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if( val.type === \"VBE\"){\n"
		"	    if(cont % 9 === 0){\n"
		"	    items.push(\"BACKEND :  \" + \"<b>\" + val.ident + \"</b><BR>\" );\n"
		"	    }\n"
		"	    items.push( \"<span>\" + val.descr + \" : \" + val.value  + \"</span><BR>\" );\n"
		"	    cont++;"
		"	    } \n"
		"	    });\n"
		"	    $(\"p4\").html(\"\");\n"
		"	    $( \"<ul/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"p4\" );\n"
		"	    });\n"
		"		};\n"
		"	  </script>\n"
		"	</div>\n"
		"      </div>\n"
		"      <hr>\n"
		"      <script>\n"
		"	function openSpoiler(id){\n"
		"	var a = document.getElementById(id).style;\n"
		"	a.display = a.display==\'block\'?\'none\':\'block\'}\n"
		"      </script>\n"
		"      <a href=\"javascript:openSpoiler(\'spoil\')\">\n"
		"	<b>Show detailed counters</b></a>\n"
		"      <div id=\"spoil\" class=\"row\" style=\"display: none;\">\n"
		"	<div class=\"col-xs-5\">\n"
		"	  <h2>Description:</h2>\n"
		"	  <p1>short description</p1>\n"
		"	  <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){description()}, 1000);\n"
		"	    function description(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if(cont>7){\n"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + val.descr + \"</span><BR>\" );\n"
		"	    i++;\n"
		"	    }\n"
		"	    cont++;\n"
		"	    });\n"
		"	    $(\"p1\").html(\"\");\n"
		"	    $( \"<ul/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"p1\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"	</div>\n"
		"	<div class=\"col-xs-5\">\n"
		"	  <h2>Name:</h2>\n"
		"	  <p2>name</p2>\n"
		"	  <script type=\"text/javascript\" style=\"float:left\">\n"
		"	    var myVar = setInterval(function(){name()}, 1000);\n"
		"	    function name(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if(cont>7){\n"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + key + \"</span><BR>\" );\n"
		"	    i++;\n"
		"	    }\n"
		"	    cont++;\n"
		"	    });\n"
		"	    $(\"p2\").html(\"\");\n"
		"	    $( \"<ul/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"p2\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"	</div>\n"
		"	<div class=\"col-xs-2\">\n"
		"	  <h2>Value:</h2>\n"
		"	  <p3>value</p3>\n"
		"	  <script type=\"text/javascript\">\n"
		"	    var myVar = setInterval(function(){value()}, 1000);\n"
		"	    function value(){\n"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {\n"
		"	    var items = [];\n"
		"	    var cont = 0;\n"
		"	    var i = 1;\n"
		"	    $.each( data, function( key, val ) {\n"
		"	    if(cont>7){\n"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + val.value + \"</span><BR>\");\n"
		"	    i++;\n"
		"	    }\n"
		"	    cont++;\n"
		"	    });\n"
		"	    $(\"p3\").html(\"\");\n"
		"	    $( \"<ul/>\", {\n"
		"	    \"class\": \"my-new-list\",\n"
		"	    html: items.join( \"\" )\n"
		"	    }).appendTo( \"p3\" );\n"
		"	    });\n"
		"	    };\n"
		"	  </script>\n"
		"	</div>\n"
		"      </div>\n"
		"      <hr>\n"
		"          <a href=\"/rtstatus.json\">Complete JSON file</a>\n"
		"	   <hr>\n"
		"      <footer>\n"
		"	<p>&copy;Copyright 2014 Varnish Software AS</p>\n"
		"      </footer>\n"
		"    </div> <!-- /container -->\n"
		"    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.4.2.min.js\"></script>\n"
		"    <!-- Latest compiled and minified CSS -->\n"
		"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\n"
		"    <!-- Optional theme -->\n"
		"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css\">\n"
		"    <!-- Latest compiled and minified JavaScript -->\n"
		"    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n"
		"    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"
		"    <!--[if lt IE 9]>\n"
		"	<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n"
		"	<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n"
		"	<![endif]-->\n"
		"  </body>\n"
		"</html>\n" ;
