char *html = 
		"<!DOCTYPE html>\n"
	"<html lang=\"en\">\n"
	"  <head>\n"
	"    <meta charset=\"utf-8\">\n"
	"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
	"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
	"    <meta name=\"description\" content=\"Varnish status frontend\">\n"
	"    <meta name=\"author\" content=\"Varnish software\">\n"
	"    <link rel=\"icon\" href=\"../../favicon.ico\">\n"
	"    <title>Varnish Status</title>\n"
	"    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.4.2.min.js\"></script>\n"
	"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\n"
	"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css\">\n"
	"    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\n"
	"    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n"
	"    <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n"
	"    <style>\n"
	"      .table-hover tbody tr:hover td{background-color: #E6E6E6;}\n"
	"      th {background-color: #f5f5f5;}\n"
	"    </style>\n"
	"  </head>\n"
	"  <body>\n"
	"    <div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n"
	"      <div class=\"container\">\n"
	"	<div class=\"collapse navbar-collapse\">\n"
	"     	  <ul class=\"nav navbar-nav\">\n"
	"            <li><a class=\"navbar-brand\"href=\"https://github.com/arianna-aondio/libvmod-rtstatus\">GITHUB</a></li>\n"
	"            <li><a class=\"navbar-brand\" href=\"/rtstatus.json\">JSON</a></li>\n"
	"      	  </ul>\n"
	"     	</div>\n"
	"      </div>\n"
	"    </div>\n"
	"</div>\n"
	"<div class=\"jumbotron\">\n"
	"  <div class=\"container\"><h1>VARNISH STATUS</h1></div>\n"
	"</div>\n"
	"<div class=\"container\">\n"
	"  <table class=\"container\" id=\"info\" style=\"white-space: pre;width: 40%;float:left;\">\n"
	"    <tbody></tbody>\n"
	"  </table>\n"
	"</div>\n"
	"<br>\n"
	"<br>\n"
	"<div class= \"container\">\n"
	"  <table class=\"container\" id=\"beover\" style=\"white-space: pre;float:left;\">\n"
	"    <thead>\n"
	"      <tr>\n"
	"	<th>Backends</th>\n"
	"	<th>Num</th>\n"
	"	<th>Req</th>\n"
	"	<th>Conn</th>\n"
	"	<th>Unhealthy</th>\n"
	"	<th>Busy</th>\n"
	"	<th>Fail</th>\n"
	"	<th>Reuse</th>\n"
	"	<th>Toolate</th>\n"
	"	<th>Recycle</th>\n"
	"	<th>Retry</th>\n"
	"      </tr>\n"
	"    </thead>\n"
	"    <tbody></tbody>\n"
	"  </table>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<br>\n"
	"<br>\n"
	"<div class=\"container\">\n"
	"  <table class=\"container table-hover\" id=\"tblbe\" style=\"white-space: pre;\">\n"
	"    <thead>\n"
	"      <tr>\n"
	"	<th>Backend name</th>\n"
	"	<th>VCLS</th>\n"
	"	<th>Healthy</th>\n"
	"	<th>Req KB/s</th>\n"
	"	<th>Req KB</th>\n"
	"	<th>Resp KB/s</th>\n"
	"	<th>Resp KB</th>\n"
	"	<th>Pipe hdr KB</th>\n"
	"	<th>Pipe out KB</th>\n"
	"	<th>Pipe in KB</th>\n"
	"      </tr>\n"
	"    </thead>\n"
	"    <tbody></tbody>\n"
	"  </table>\n"
	"  <a href=\"javascript:openSpoiler('spoil')\"><b>Show detailed counters</b></a>\n"
	"  <div id=\"spoil\" class=\"row\" style=\"display: none;\">\n"
	"    <div class=\"container\">\n"
	"      <table class=\"container table-hover\" id=\"tbl\" style=\"white-space: pre;\">\n"
	"	<thead><tr><th>Description</th><th>Name</th><th>Value</th></tr></thead>\n"
	"	<tbody></tbody>\n"
	"      </table>\n"
	"    </div>\n"
	"  </div>\n"
	"  <hr>\n"
	"</div>\n"
	"<div class=\"footer\">\n"
	"  <div class=\"container\">\n"
	"    <p>&copy;Copyright 2014 Varnish Software AS</p>\n"
	"  </div>\n"
	"</div>\n"
	"<script>\n"
	"function openSpoiler(id){\n"
	"	var a = document.getElementById(id).style;\n"
	"	a.display = a.display=='block'?'none':'block'}\n"
	"function openSpoiler(id){\n"
	"	var a = document.getElementById(id).style;\n"
	"	a.display = a.display=='block'?'none':'block'}\n"
	"function info(){\n"
	"	loadFileJSON_resp('myJson', \"/rtstatus.json\");\n"
	"};\n"
	"var enter=0;\n"
	"var sum_json=[];\n"
	"var val_json_body;var val_json_hdr;\n"
	"var id_json_hdr;\n"
	"var id_json_body;\n"
	"function loadFileJSON_resp( toLocalStorage, fromUrl){\n"
	""
	"	var k=0;\n"
	"	var sum_json_req=[];\n"
	"	var a=0;\n"
	"	var val_json_body;var val_json_hdr;\n"
	"	var id_json_hdr;\n"
	"	var id_json_body;\n"
	"	var c=2;\n"
	"	var sum_json_pipe=[];\n"
	"	var val_json_body_pipe;var val_json_hdr_pipe;\n"
	"	var id_json_hdr_pipe;\n"
	"	var id_json_body_pipe;\n"
	"	var diff_beresp=[];\n"
	"	var diff_bereq=[];\n"
	"	var diff_interval_resp=[];\n"
	"	var diff_interval_req=[];\n"
	"	if (localStorage[toLocalStorage]){\n"
	"		printFileJson(toLocalStorage);\n"
	"		$.getJSON(   \"/rtstatus.json\"   , function(data) {\n"
	"			var flag=0;\n"
	"			$.each( data, function(chiave, valore){\n"
	"				if(chiave.match(\"beresp_hdrbytes\")){\n"
	"					val_json_hdr = valore.value;\n"
	"					id_json_hdr=valore.ident;\n"
	"				}\n"
	"				if(chiave.match(\"beresp_bodybytes\")){\n"
	"					val_json_body = valore.value;\n"
	"					id_json_body=valore.ident;\n"
	"					if( id_json_hdr===id_json_body){\n"
	"						k++;\n"
	"						sum_json[k]=val_json_hdr+  val_json_body   ;\n"
	"						if(typeof sum_json[k]===\"undefined\" || typeof tmp_resp[k]===\"undefined\" ||(sum_json[k]-tmp_resp[k])<0 ){\n"
	"							diff_beresp[k]=0;\n"
	"						}else{   \n"
	"							diff_beresp[k]= (sum_json[k]-tmp_resp[k]);\n"
	"							diff_interval_resp[k]=data.uptime_sec-interval_resp[k];\n"
	"						}\n"
	"				}}\n"
	"				if(chiave.match(\"bereq_hdrbytes\")){\n"
	"					val_json_hdr = valore.value;\n"
	"					id_json_hdr=valore.ident;\n"
	"				}\n"
	"				if(chiave.match(\"bereq_bodybytes\")){\n"
	"					val_json_body = valore.value;\n"
	"					id_json_body=valore.ident;\n"
	"					if( id_json_hdr===id_json_body){\n"
	"						a++;\n"
	"						sum_json_req[a]=val_json_hdr+  val_json_body;\n"
	"						if(typeof sum_json_req[a]===\"undefined\" || typeof tmp_req[a]===\"undefined\" ||(sum_json_req[a]-tmp_req[a])<0 ){\n"
	"							diff_bereq[a]=0;\n"
	"						}else{\n"
	"							diff_bereq[a]=   (sum_json_req[a]-tmp_req[a]);\n"
	"							diff_interval_req[a]=data.uptime_sec-interval_req[a];\n"
	"						}\n"
	"				}}\n"
	"		});\n"
	"$('table#info TBODY').html(\"\");\n"
	"$('table#info TBODY').append('<tr><td>'+\"<b>Varnish version: </b> \"+'</td><td>'+data.varnish_version +'</td><td></tr>');\n"
	"$('table#info TBODY').append('<tr><td>'+\"<b>Server identity: </b> \"+'</td><td>'+data.server_id +'</td><td></tr>');\n"
	"$('table#info TBODY').append('<tr><td>'+\"<b>Varnish uptime: </b> \"+'</td><td>'+data.uptime +'</td><td></tr>');\n"
	"$('table#info TBODY').append('<tr><td>'+\"<b>Hitrate: </b> \"+'</td><td>'+data.hitrate + ' %'+'</td><td></tr>');\n"
	"$('table#info TBODY').append('<tr><td>'+\"<b>Load: </b> \"+'</td><td>'+data.load +' req/s'+'</td><td></tr>');\n"
	"var tmp=[];\n"
	"var cont =0;\n"
	"$('table#beover TBODY').html(\"\");\n"
	"$.each( data, function( key, val ){\n"
	"	if(val.type === \"MAIN\" && key.match(\"backend\")){\n"
	"		tmp.push( \"<p>\" +  val.value + \"</p>\" );\n"
	"}});\n"
	"$('table#beover TBODY').append('<tr><td>'+\"      \"+'</td><td>'+tmp[8]+'</td><td>'+tmp[9]+'</td><td>'+tmp[0]+'</td><td>'+tmp[1]+'</td><td>'+tmp[2]+'</td><td>'+tmp[3]+'</td><td>'+tmp[4]+'</td><td>'+tmp[5]+'</td><td>'+tmp[6]+'</td><td>'+tmp[7]+'</td><td></tr>');\n"
	"var cont = 0;\n"
	"var flag = 0;\n"
	"var items=[];\n"
	"var ix=1;\n"
	"$('table#tblbe TBODY').html(\"\");\n"
	"$.each(data, function(key, val){\n"
	"	if(key.match(\"VBE\")){\n"
	"		cont++;\n"
	"	switch(cont){\n"
	"	case 1: var tmp1 = val.value;\n"
	"			items.push(tmp1);\n"
	"			break;\n"
	"	case 2: var tmp2 = val.value;\n"
	"			items.push(tmp2);\n"
	"			break;\n"
	"	case 3: var tmp3 = val.value;\n"
	"			items.push(tmp3);\n"
	"			break;\n"
	"	case 4: var tmp4 = val.value;\n"
	"			items.push(tmp4);\n"
	"			break;\n"
	"	case 5: var tmp5 = val.value;\n"
	"			items.push(tmp5);\n"
	"			break;\n"
	"	case 6: var tmp6 = val.value;\n"
	"			items.push(tmp6);\n"
	"			break;\n"
	"	case 7: var tmp7 = val.value;\n"
	"			items.push(tmp7);\n"
	"			break;\n"
	"	case 8: var tmp8 = val.value;\n"
	"			items.push(tmp8);\n"
	"			break;\n"
	"	case 9: var tmp9 = val.value;\n"
	"			items.push(tmp9);\n"
	"			break;\n"
	"	};\n"
	"if(cont === 9){\n"
	"if(diff_interval_req[ix]===0)\n"
	" 	var difference1= 0;\n"
	"else\n"
	"	difference1= Math.round((diff_bereq[(ix)]/(diff_interval_req[ix])));\n"
	"if(diff_interval_resp[ix]===0)\n"
	" 	var difference2= 0;\n"
	"else\n"
	"	difference2= Math.round((diff_beresp[(ix)]/(diff_interval_resp[ix])));\n"
	"	$('table#tblbe TBODY').append('<tr><td>'+val.ident+'</td><td>'+items[0]+'</td><td>'+data.backend[(ix-1)].value+'</td><td>'+Math.round(difference1/1000)+'</td><td>'+Math.round(((items[2]+items[3])/1000))+'</td><td>'+Math.round((difference2/1000))+'</td><td>'+Math.round(((items[4]+items[5])/1000))+'</td><td>'+Math.round((items[6]/1000)) +'</td><td>'+Math.round((items[7]/1000))+'</td><td>'+Math.round((items[8]/1000))+'</td></tr>');\n"
	"	items=[];\n"
	"	cont = 0;\n"
	"	ix++;\n"
	"}\n"
	"};\n"
	"});\n"
	"var cont = 0;\n"
	"$('table#tbl TBODY').html(\"\");\n"
	"$.each(data, function(key, val){\n"
	"	if(cont > 7){\n"
	"		$('table#tbl TBODY').append('<tr><td>'+key+'</td><td>'+val.descr+'</td><td>'+val.value+'</td><td></tr>');\n"
	"	}\n"
	"cont++;\n"
	"});\n"
	"localStorage[toLocalStorage] = JSON.stringify(data);\n"
	"});\n"
	"}\n"
	"else {\n"
	"	$.getJSON(   \"/rtstatus.json\"   , function(data) { \n"
	"		localStorage[toLocalStorage] = JSON.stringify(data);\n"
	"	});\n"
	"	}\n"
	"}\n"
	"var tmp_resp=[];\n"
	"var resp_h_val=0;\n"
	"var resp_b_val=0;\n"
	"var id_hdr_resp,id_body_resp;\n"
	"var cont_resp =0;\n"
	"var tmp_req=[];\n"
	"var req_h_val=0;\n"
	"var req_b_val=0;\n"
	"var id_hdr_req,id_body_req;\n"
	"var cont_req =0;\n"
	"var m=0;\n"
	"var i=0;\n"
	"var interval_req=[];\n"
	"var interval_resp=[];\n"
	"function printFileJson(toLocalStorage){\n"
	"var myJSON = JSON.parse(localStorage.myJson);\n"
	"	$.each( myJSON, function(key, val){\n"
	"		if(key.match(\"beresp_hdrbytes\")){\n"
	"			resp_h_val = val.value;\n"
	"			id_hdr_resp = val.ident;\n"
	"			cont_resp++;\n"
	"		}\n"
	"		if(key.match(\"beresp_bodybytes\")){\n"
	"			resp_b_val = val.value;\n"
	"			id_body_resp = val.ident;\n"
	"			cont_resp++;\n"
	"		}\n"
	"		if(key.match(\"bereq_hdrbytes\")){\n"
	"			req_h_val = val.value;\n"
	"			id_hdr_req = val.ident;\n"
	"			cont_req++;\n"
	"		}\n"
	"		if(key.match(\"bereq_bodybytes\")){\n"
	"			req_b_val = val.value;\n"
	"			id_body_req = val.ident;\n"
	"			cont_req++;\n"
	"		}\n"
	"		if(id_hdr_resp===id_body_resp && cont_resp===2){\n"
	"			i++;\n"
	"			tmp_resp[i]= resp_h_val+resp_b_val;\n"
	"			cont_resp=0;\n"
	"			interval_resp[i]=(myJSON.uptime_sec-1);\n"
	"		}\n"
	"		if(id_hdr_req===id_body_req && cont_req===2){\n"
	"			m++;\n"
	"			tmp_req[m]= req_h_val+req_b_val;\n"
	"			cont_req=0;\n"
	"			interval_req[m]=(myJSON.uptime_sec-1);\n"
	"		}\n"
	"	});\n"
	"i=0;\n"
	"m=0;\n"
	"};\n"
	"var myVar = setInterval(function(){info();}, 1000);\n"
	"</script>\n"
	"</body>\n"
	"</html>\n"
;
