
char *html = 		"<!DOCTYPE html>"
		"<html lang=\"en\">"
		"  <head>"
		"    <meta charset=\"utf-8\">"
		"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
		"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
		"    <meta name=\"description\" content=\"\">"
		"    <meta name=\"author\" content=\"\">"
		"    <link rel=\"icon\" href=\"../../favicon.ico\">"
		"    <title>Varnish Status</title>"
		"    <!-- Latest compiled and minified CSS -->"
		"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">"
		"    <!-- Optional theme -->"
		"    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css\">"
		"    <!-- Latest compiled and minified JavaScript -->"
		"    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>"
		"    <!-- Custom styles for this template -->"
		"    <link href=\"jumbotron.css\" rel=\"stylesheet\">"
		"    <!-- Just for debugging purposes. Don\'t actually copy these 2 lines! -->"
		"    <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->"
		"    <script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>"
		"    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->"
		"    <!--[if lt IE 9]>"
		"	<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>"
		"	<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>"
		"	<![endif]-->"
		"    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.4.2.min.js\"></script>"
		"  </head>"
		"  <body>"
		"    <div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">"
		"      <div class=\"container\">"
		"        <div class=\"navbar-header\">"
		"          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">"
		"            <span class=\"sr-only\">Toggle navigation</span>"
		"            <span class=\"icon-bar\"></span>"
		"            <span class=\"icon-bar\"></span>"
		"            <span class=\"icon-bar\"></span>"
		"          </button>"
		"          <a class=\"navbar-brand\" href=\"https://github.com/arianna-aondio/libvmod-rtstatus\">Github repository</a>"
		"        </div>"
		"      </div>"
		"    </div>"
		"    <!-- Main jumbotron for a primary marketing message or call to action -->"
		"    <div class=\"jumbotron\">"
		"      <div class=\"container\">"
		"        <h1>VARNISH STATUS</h1>"
		"      </div>"
		"    </div>"
		"    <div class=\"container\">"
		"      <!-- Example row of columns -->"
		"      <div class=\"row\">"
		"        <div class=\"col-md-4\" id=\"info\">"
		"          <h2>General infos</h2>"
		"          <script type=\"text/javascript\">"
		"	    var myVar = setInterval(function(){info()}, 1000);"
		"	    function info(){"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];	"
		"	    var index = 0;"
		"	    items.push(\"<p>\"+ \"<b>Varnish version: </b> \" + data.varnish_version + \",\" + \"</p>\");"
		"	    items.push(\"<p>\"+ \"<b>Server identity: </b> \" + data.server_id + \",\" + \"</p>\");"
		"	    items.push(\"<p>\"+ \"<b>Client identity: </b> \" + data.client_id + \",\" + \"</p>\");"
		"	    items.push(\"<p>\"+ \"<b>Varnish Uptime: </b> \" + data.uptime + \" s\" + \"</p>\");"
		"	    items.push(\"<p>\"+ \"<b>Hitrate: </b>\"+ \" \" + data.hitrate + \" %\"+ \"</p>\");"
		"	    items.push(\"<p>\"+ \"<b>Load: </b>\"+ \" \" + data.load + \" req/s\"+ \"</p>\");"
		"	    $(\"#info\").html(\"\");"
		"	    $( \"<p/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"#info\" );"
		"	    })();"
		"	    };"
		"	    info();"
		"	  </script>"
		"        </div>"
		"	<div class=\"col-md-2\"></div>"
		"        <div class=\"col-md-3\" id=\"be\">"
		"          <h2>Backends overview</h2>"
		"          <script type=\"text/javascript\">"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if( val.type === \"MAIN\" && key.contains(\'backend\')){"
		"	    items.push( \"<p>\" + \"<b>\" + val.descr + \"</b>\"  +\" :  \" + \"</p>\" );"
		"	    }});"
		"	    $(\"#be\").html(\"\");"
		"	    $( \"<p/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"#be\" );"
		"	    })();"
		"	  </script>"
		"        </div>"
		"	<div class=\"col-md-1\" id=\"bevalue\">"
		"	  <script type=\"text/javascript\">"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if( val.type === \"MAIN\" && key.contains(\'backend\')){"
		"	    items.push( \"<p>\" +  val.value + \"</p>\" );"
		"	    }});"
		"	    $(\"#bevalue\").html(\"\");"
		"	    $( \"<p/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"#bevalue\" );"
		"	    })();"
		"	  </script>"
		"	</div>"
		"      </div>"
		"      <hr>"
		"      <h1>Backends:</h1>"
		"      <div class=\"spoiler\">"
		"	<div class=\"backend\">"
		"	  <script type=\"text/javascript\">"
		"	    var myVar = setInterval(function(){backend()}, 1000);"
		"	    function backend(){"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var i,j;"
		"	    var cont;"
		"	    $.each( data, function( key, val ) {"
		"	    if(key === \"backend\"){"
		"	    var tmp = data.backend;"
		"	    }"
		"	    if(tmp) {"
		"	    for(i = 0, cont = 0; i < tmp.length;i++){"
		"	    items.push( \"<p>\" + \"<b>Name: </b> \" + tmp[i].name + \" : \" + tmp[i].value + \",\" + \"</p>\" );"
		"	    }}});"
		"	    $(\"div.backend\").html(\"\");"
		"	    $( \"<p/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"div.backend\" );"
		"	    })();"
		"	    };"
		"	    backend();"
		"	  </script>       "
		"	</div>"
		"      </div>"
		"      <script>"
		"	function openSpoiler(id){"
		"	var a = document.getElementById(id).style;"
		"	a.display = a.display==\'block\'?\'none\':\'block\'}"
		"      </script>"
		"      <BR>"
		"      <a href=\"javascript:openSpoiler(\'spoilbe\')\">"
		"	<b>Show details backends</b></a>"
		"      <div id=\"spoilbe\" class=\"row\" style=\"display: none;\">"
		"	<div class=\"col-xs-5\">"
		"	  <h2>Details:</h2>"
		"	  <p4>details</p4>"
		"	  <script type=\"text/javascript\">"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if( val.type === \"VBE\"){"
		"	    if(cont % 9 === 0){"
		"	    items.push(\"BACKEND :  \" + \"<b>\" + val.ident + \"</b><BR>\" );"
		"	    }"
		"	    items.push( \"<span>\" + val.descr + \" : \" + val.value  + \"</span><BR>\" );"
		"	    cont++;"
		"	    } "
		"	    });"
		"	    $(\"p4\").html(\"\");"
		"	    $( \"<ul/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"p4\" );"
		"	    })();"
		"	  </script>"
		"	</div>"
		"      </div>"
		"      <hr>"
		"      <script>"
		"	function openSpoiler(id){"
		"	var a = document.getElementById(id).style;"
		"	a.display = a.display==\'block\'?\'none\':\'block\'}"
		"      </script>"
		"      <a href=\"javascript:openSpoiler(\'spoil\')\">"
		"	<b>Show detailed counters</b></a>"
		"      <div id=\"spoil\" class=\"row\" style=\"display: none;\">"
		"	<div class=\"col-xs-5\">"
		"	  <h2>Description:</h2>"
		"	  <p1>short description</p1>"
		"	  <script type=\"text/javascript\">"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if(cont>7){"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + \"[\" + val.descr + \"]\" + \"</span><BR>\" );"
		"	    i++;"
		"	    }"
		"	    cont++;"
		"	    });"
		"	    $(\"p1\").html(\"\");"
		"	    $( \"<ul/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"p1\" );"
		"	    })();"
		"	  </script>"
		"	</div>"
		"	<div class=\"col-xs-5\">"
		"	  <h2>Name:</h2>"
		"	  <p2>name</p2>"
		"	  <script type=\"text/javascript\" style=\"float:left\">"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if(cont>7){"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + \"[\" + key + \"]\" + \"</span><BR>\" );"
		"	    i++;"
		"	    }"
		"	    cont++;"
		"	    });"
		"	    $(\"p2\").html(\"\");"
		"	    $( \"<ul/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"p2\" );"
		"	    })();"
		"	  </script>"
		"	</div>"
		"	<div class=\"col-xs-2\">"
		"	  <h2>Value:</h2>"
		"	  <p3>value</p3>"
		"	  <script type=\"text/javascript\">"
		"	    var myVar = setInterval(function(){value()}, 1000);"
		"	    function value(){"
		"	    $.getJSON( \"/rtstatus.json\", function( data ) {"
		"	    var items = [];"
		"	    var cont = 0;"
		"	    var i = 1;"
		"	    $.each( data, function( key, val ) {"
		"	    if(cont>7){"
		"	    items.push( \"<span>\" + \"<sub>\"+ i + \". \" + \"</sub>\" + val.value + \"</span><BR>\");"
		"	    i++;"
		"	    }"
		"	    cont++;"
		"	    });"
		"	    $(\"p3\").html(\"\");"
		"	    $( \"<ul/>\", {"
		"	    \"class\": \"my-new-list\","
		"	    html: items.join( \"\" )"
		"	    }).appendTo( \"p3\" );"
		"	    })();"
		"	    };"
		"	    value();"
		"	  </script>"
		"	</div>"
		"      </div>"
		"      <hr>"
		"          <a href=\"/rtstatus.json\">Complete JSON file</a>"
		"	   <hr>"
		"      <footer>"
		"	<p>&copy;Copyright 2014 Varnish Software AS</p>"
		"      </footer>"
		"    </div> <!-- /container -->"
		"    <!-- Bootstrap core JavaScript"
		"	 ================================================== -->"
		"    <!-- Placed at the end of the document so the pages load faster -->"
		"    <script src=\"../../dist/js/bootstrap.min.js\"></script>"
		"    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->"
		"    <script src=\"../../assets/js/ie10-viewport-bug-workaround.js\"></script>"
		"  </body>"
		"</html>"


    ;
