#!/usr/bin/env python
from sys import argv
from os.path import basename

# Based on http://stackoverflow.com/questions/14945095/how-to-escape-string-for-generated-c
def enc(s):
   s = s[:-1]  # Remove \n.
   result = ''
   for c in s:
      if not (32 <= ord(c) < 127) or c in ('\\', '"'):
         result += '\\%03o' % ord(c)
      else:
         result += c
   return '"' + result + '"'

if __name__ == "__main__":
    print("/* This file is generated by %s. Do not edit. */\n" % argv[0])
    print("char *html = \\")
    for line in map(enc, open(argv[1])):
        print("  " + line + " \\")
    print(";")
