/* This file is generated by cstring.py. Do not edit. */

char html[] = \
    "<!DOCTYPE html>\n" \
    "<html lang=\042en\042>\n" \
    "<head>\n" \
    "  <meta charset=\042utf-8\042>\n" \
    "  <meta http-equiv=\042X-UA-Compatible\042 content=\042IE=edge\042>\n" \
    "  <meta name=\042viewport\042 content=\042width=device-width, initial-scale=1\042>\n" \
    "  <meta name=\042description\042 content=\042Varnish Cache status\042>\n" \
    "  <meta name=\042author\042 content=\042Varnish Software\042>\n" \
    "  <title>Varnish Status</title>\n" \
    "  <script type=\042text/javascript\042 src=\042https://code.jquery.com/jquery-1.11.2.min.js\042></script>\n" \
    "  <link rel=\042stylesheet\042 href=\042https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\042>\n" \
    "  <link rel=\042stylesheet\042 href=\042https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css\042>\n" \
    "  <script src=\042https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\042></script>\n" \
    "  <script src=\042https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\042></script>\n" \
    "  <script src=\042https://oss.maxcdn.com/respond/1.4.2/respond.min.js\042></script>\n" \
    "  <style>\n" \
    "    .table-hover { border-bottom:0px !important; }\n" \
    "    .table-hover th, .table-hover td { border: 1px !important; }\n" \
    "    .table-hover tbody tr:hover td { background-color: #E6E6E6; }\n" \
    "  </style>\n" \
    "</head>\n" \
    "<body>\n" \
    "<div class=\042navbar navbar-inverse navbar-fixed-top\042 role=\042navigation\042>\n" \
    "  <div class=\042container\042>\n" \
    "        <div class=\042collapse navbar-collapse\042>\n" \
    "          <ul class=\042nav navbar-nav\042>\n" \
    "                <li><a class=\042navbar-brand\042href=\042https://github.com/varnish/libvmod-rtstatus\042>Github</a></li>\n" \
    "                <li><a class=\042navbar-brand\042 href=\042/rtstatus.json\042>JSON</a></li>\n" \
    "          </ul>\n" \
    "        </div>\n" \
    "  </div>\n" \
    "</div>\n" \
    "<div class=\042jumbotron\042>\n" \
    "  <div class=\042container\042>\n" \
    "    <h1>Varnish Cache status</h1>\n" \
    "  </div>\n" \
    "</div>\n" \
    "<div class=\042container\042>\n" \
    "  <table class=\042container\042 id=\042info\042 style=\042white-space: pre;width: 40%;float:left;\042>\n" \
    "    <tbody>\n" \
    "    <!-- populated by JS? -->\n" \
    "    </tbody>\n" \
    "  </table>\n" \
    "</div>\n" \
    "<br>\n" \
    "<br>\n" \
    "<div class= \042container\042>\n" \
    "  <table class=\042table table-hover\042 id=\042beover\042 style=\042white-space: pre;float:left;\042>\n" \
    "    <thead>\n" \
    "      <tr>\n" \
    "        <th>Backends</th>\n" \
    "        <th>Num</th>\n" \
    "        <th>Req</th>\n" \
    "        <th>Conn</th>\n" \
    "        <th>Unhealthy</th>\n" \
    "        <th>Busy</th>\n" \
    "        <th>Fail</th>\n" \
    "        <th>Reuse</th>\n" \
    "        <th>Recycle</th>\n" \
    "        <th>Retry</th>\n" \
    "      </tr>\n" \
    "    </thead>\n" \
    "    <tbody>\n" \
    "      <!-- populated by JS? -->\n" \
    "    </tbody>\n" \
    "  </table>\n" \
    "</div>\n" \
    "<br>\n" \
    "<br>\n" \
    "<div class=\042container\042>\n" \
    "  <table class=\042table table-hover\042 id=\042tblbe\042 style=\042white-space: pre;\042>\n" \
    "    <thead>\n" \
    "      <tr>\n" \
    "        <th>Backend name</th>\n" \
    "        <th title=\042Health based on probe\042>Probe health</th>\n" \
    "        <th title=\042Backend request KBytes per sec\042>Req KB/s</th>\n" \
    "        <th title=\042Total backend request KBytes sent\042>Requests</th>\n" \
    "        <th title=\042Backend response KBytes per sec\042>Resp KB/s</th>\n" \
    "        <th title=\042Total backend response KBytes received\042>Responses</th>\n" \
    "        <th title=\042Pipe request header KBytes\042>Pipe hdr</th>\n" \
    "        <th title=\042Piped KBytes from backend\042>Pipe out</th>\n" \
    "        <th title=\042Piped KBytes to backend\042>Pipe in</th>\n" \
    "        <th title=\042Connections to backend\042>Conn</th>\n" \
    "        <th title=\042Concurrent requests to backend\042>Req</th>\n" \
    "      </tr>\n" \
    "    </thead>\n" \
    "    <tbody>\n" \
    "    </tbody>\n" \
    "  </table>\n" \
    "  <a href=\042javascript:openSpoiler('spoil')\042><b>Show detailed counters</b></a>\n" \
    "  <div id=\042spoil\042 class=\042row\042 style=\042display: none;\042>\n" \
    "    <div class=\042container\042>\n" \
    "      <table class=\042container table-hover\042 id=\042tbl\042 style=\042white-space: pre;\042>\n" \
    "        <thead><tr><th>Description</th><th>Name</th><th>Value</th></tr></thead>\n" \
    "        <tbody></tbody>\n" \
    "      </table>\n" \
    "    </div>\n" \
    "  </div>\n" \
    "  <hr>\n" \
    "</div>\n" \
    "<div class=\042footer\042>\n" \
    "  <div class=\042container\042>\n" \
    "    <p>Copyright &copy; 2015-2016 Varnish Software</p>\n" \
    "  </div>\n" \
    "</div>\n" \
    "<script>\n" \
    "\n" \
    "function openSpoiler(id) {\n" \
    "  var a = document.getElementById(id).style;\n" \
    "  a.display = a.display == 'block' ? 'none' : 'block'\n" \
    "}\n" \
    "\n" \
    "var myJSON\n" \
    "var dataToStore;\n" \
    "var localJSON;\n" \
    "var localJson;\n" \
    "\n" \
    "function loadJSON() {\n" \
    "  $.ajax({\n" \
    "    url: \042/rtstatus.json\042,\n" \
    "    success: function(json) {\n" \
    "      localStorage.setItem('json', JSON.stringify(json));\n" \
    "    }\n" \
    "  });\n" \
    "}\n" \
    "\n" \
    "function info() {\n" \
    "  localJson = JSON.parse(localStorage.getItem('json'));\n" \
    "\n" \
    "  $.each(localJson, function(key, val) {\n" \
    "    $('table#info TBODY').html(\042\042);\n" \
    "    $('table#info TBODY').append('<tr><td>' + \042<b>Varnish version: </b> \042 + '</td><td>' + localJson.varnish_version + '</td></tr>');\n" \
    "    $('table#info TBODY').append('<tr><td>' + \042<b>Varnish uptime: </b> \042 + '</td><td>' + localJson.uptime + '</td></tr>');\n" \
    "    $('table#info TBODY').append('<tr><td>' + \042<b>Hit ratio: </b> \042 + '</td><td>' + localJson.absolute_hitrate + ' %' + '</td></tr>');\n" \
    "    $('table#info TBODY').append('<tr><td>' + \042<b>Average hitrate: </b> \042 + '</td><td>' + localJson.avg_hitrate + ' %' + '</td></tr>');\n" \
    "    $('table#info TBODY').append('<tr><td>' + \042<b>Average load: </b> \042 + '</td><td>' + localJson.avg_load + ' req/s' + '</td></tr>');\n" \
    "  });\n" \
    "}\n" \
    "\n" \
    "function beOverView() {\n" \
    "  var tmp = [];\n" \
    "  $('table#beover TBODY').html(\042\042);\n" \
    "  $.each(localJson, function(key, val) {\n" \
    "    if (val.type === \042MAIN\042 && key.match(\042backend\042)) {\n" \
    "      tmp.push(\042<p>\042 + val.value + \042</p>\042);\n" \
    "    }\n" \
    "  });\n" \
    "  $('table#beover TBODY').append('<tr><td>' + \042      \042 + '</td><td>' + tmp[7] + '</td><td>' + tmp[8] + '</td><td>' + tmp[0] + '</td><td>' + tmp[1] + '</td><td>' + tmp[2] + '</td><td>' + tmp[3] + '</td><td>' + tmp[4] + '</td><td>' + tmp[5] + '</td><td>' + tmp[6] + '</td><td></tr>');\n" \
    "}\n" \
    "\n" \
    "function spoiler() {\n" \
    "  $('table#tbl TBODY').html(\042\042);\n" \
    "  $.each(localJson, function(key, val) {\n" \
    "    if (val.type === \042MAIN\042 || val.type === \042MGT\042 || val.type === \042MEMPOOL\042 || val.type === \042VBE\042 || val.type === \042LCK\042) {\n" \
    "      $('table#tbl TBODY').append('<tr><td>' + key + '</td><td>' + val.descr + '</td><td>' + val.value + '</td><td></tr>');\n" \
    "    }\n" \
    "  });\n" \
    "}\n" \
    "\n" \
    "function beCollect() {\n" \
    "  var cont = 0;\n" \
    "  $('table#tblbe TBODY').html(\042\042);\n" \
    "\n" \
    "  $.each(localJson, function(key, val) {\n" \
    "      if (key.match(\042 VBE \042)) {\n" \
    "      cont++;\n" \
    "      switch (cont) {\n" \
    "        case 1:\n" \
    "          var tmp1 = val.value;\n" \
    "          items.push(tmp1);\n" \
    "          break;\n" \
    "        case 2:\n" \
    "          var tmp2 = val.value;\n" \
    "          items.push(tmp2);\n" \
    "          break;\n" \
    "        case 3:\n" \
    "          var tmp3 = val.value;\n" \
    "          items.push(tmp3);\n" \
    "          break;\n" \
    "        case 4:\n" \
    "          var tmp4 = val.value;\n" \
    "          items.push(tmp4);\n" \
    "          break;\n" \
    "        case 5:\n" \
    "          var tmp5 = val.value;\n" \
    "          items.push(tmp5);\n" \
    "          break;\n" \
    "        case 6:\n" \
    "          var tmp6 = val.value;\n" \
    "          items.push(tmp6);\n" \
    "          break;\n" \
    "        case 7:\n" \
    "          var tmp7 = val.value;\n" \
    "          items.push(tmp7);\n" \
    "          break;\n" \
    "        case 8:\n" \
    "          var tmp8 = val.value;\n" \
    "          items.push(tmp8);\n" \
    "          break;\n" \
    "        case 9:\n" \
    "          var tmp9 = val.value;\n" \
    "          items.push(tmp9);\n" \
    "          break;\n" \
    "      };\n" \
    "    }\n" \
    "  });\n" \
    "}\n" \
    "\n" \
    "var items = [];\n" \
    "var prev_req = [];\n" \
    "var prev_resp = [];\n" \
    "\n" \
    "function beDetails() {\n" \
    "  var len = localJson.be_info.length;\n" \
    "  for (var i=0; i < len; i++) {\n" \
    "    $('table#tblbe TBODY').append('<tr><td>' + localJson.be_info[i].server_name + '</td><td>' + localJson.be_info[i].happy + '</td><td>' + Math.round(localJson.be_info[i].bereq_tot - prev_req[i]) + '</td><td>' + localJson.be_info[i].bereq_tot + '</td><td>' + Math.round(localJson.be_info[i].beresp_tot - prev_resp[i]) + '</td><td>' + localJson.be_info[i].beresp_tot + '</td><td>' + localJson.be_info[i].pipe_hdrbytes + '</td><td>' + localJson.be_info[i].pipe_out + '</td><td>' + localJson.be_info[i].pipe_in + '</td><td>' + localJson.be_info[i].conn + '</td><td>' + localJson.be_info[i].req + '</td></tr>');\n" \
    "    prev_req[i] = localJson.be_info[i].bereq_tot;\n" \
    "    prev_resp[i] = localJson.be_info[i].beresp_tot;\n" \
    "  }\n" \
    "}\n" \
    "\n" \
    "function main() {\n" \
    "  try {\n" \
    "    loadJSON();\n" \
    "    info();\n" \
    "    beOverView();\n" \
    "    beCollect();\n" \
    "    beDetails();\n" \
    "    spoiler();\n" \
    "    localStorage.removeItem('json');\n" \
    "  } catch (e) {}\n" \
    "}\n" \
    "setInterval(function() { main(); }, 1000);\n" \
    "\n" \
    "</script>\n" \
    "</body>\n" \
    "</html>\n" \
;
